edo:
  kinematics_solver: edo_edo/IKFastKinematicsPlugin
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0005
  kinematics_solver_timeout: 0.01
  #kinematics_solver_attempts: 3 #deprecated